n = input('Digite algo aqui: ')
print(n, 'é um numero?')
print(n.isnumeric())
print(n, 'é um alphanumérico?')
print(n.isalnum())
print(n, 'é uma letra maiúscula?')
print(n.isupper())
print(n, 'é uma letra minúscula?')
print(n.islower())
print(n, 'é um número decimal?')
print(n.isdecimal())