phrase = str(input('Digite uma frase: ')).strip().upper()
first_position = phrase.find('A')
print(f'A primeira posição que a letra A aparece é a posição {first_position+1}')
num_of_ap = phrase.count('A')
print(f'A letra A aparece {num_of_ap} vezes')
last_position = phrase.rfind('A')
print(f'A última vez que a letra A aparece é na posição {last_position+1}')