nome = input('Qual é o seu nome? ')
idade = input('Qual é a sua idade? ')
peso = input('Qual é o seu peso? ')
comida = input('Qual é a sua comida preferida? ')
amor = input('Qual é o nome do seu amor? ')
time = input('Pra qual time você torce? ')
cidade = input('Qual a cidade em que você nasceu? ')
inseto = input('Qual é o inseto que voce mais odeia? ')

print('Meu nome é', nome,', eu peso', peso, 'kgs e tenho', idade, 'anos.')
print('O amor da minha vida é o', amor, 'e eu amo quando ele faz', comida, 'pra mim.')
print('A salsicha dele é a melhor.')
print('O time do meu coração é o', time, 'mas infelizmente eu sou uma das 10 pessoas')
print('vivas que ainda tocem pra ele.')
print('Eu nasci na cidade de', cidade, 'mas costumo dizer que sou de São Paulo')
print('pra nao falarem que eu sou da roça.')
print('Se eu comer uma', inseto, 'eu morro =/')